name: pytorch-deepdream
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.8.10
  - pip==20.0.2
  - matplotlib==3.7.2
  - pytorch==2.0.1
  - torchvision==0.15.2
  - pip:
    - numpy==1.24.4
    - scipy==1.10.1
    - opencv-python==4.8.0.76
    - imageio==2.31.2
    - jupyter==1.0.0
    - git+https://github.com/openai/CLIP.git
    - regex==2023.8.8
    - ftfy==6.1.1
    - open_clip_torch==2.20.0

